# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(438, 372)
        Form.setMinimumSize(QtCore.QSize(438, 372))
        Form.setMaximumSize(QtCore.QSize(438, 372))
        Form.setStyleSheet("QWidget{\n"
"    font-size:16px;\n"
"}")
        self.db_panel_server_cb = QtWidgets.QComboBox(Form)
        self.db_panel_server_cb.setGeometry(QtCore.QRect(30, 120, 381, 30))
        self.db_panel_server_cb.setMinimumSize(QtCore.QSize(0, 30))
        self.db_panel_server_cb.setEditable(True)
        self.db_panel_server_cb.setCurrentText("")
        self.db_panel_server_cb.setObjectName("db_panel_server_cb")
        self.db_panel_server_lab_2 = QtWidgets.QLabel(Form)
        self.db_panel_server_lab_2.setGeometry(QtCore.QRect(30, 90, 381, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_panel_server_lab_2.sizePolicy().hasHeightForWidth())
        self.db_panel_server_lab_2.setSizePolicy(sizePolicy)
        self.db_panel_server_lab_2.setObjectName("db_panel_server_lab_2")
        self.db_panel_port_lab = QtWidgets.QLabel(Form)
        self.db_panel_port_lab.setGeometry(QtCore.QRect(30, 170, 381, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_panel_port_lab.sizePolicy().hasHeightForWidth())
        self.db_panel_port_lab.setSizePolicy(sizePolicy)
        self.db_panel_port_lab.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.db_panel_port_lab.setObjectName("db_panel_port_lab")
        self.db_panel_port_le = QtWidgets.QLineEdit(Form)
        self.db_panel_port_le.setGeometry(QtCore.QRect(31, 195, 111, 30))
        self.db_panel_port_le.setMinimumSize(QtCore.QSize(60, 30))
        self.db_panel_port_le.setText("")
        self.db_panel_port_le.setObjectName("db_panel_port_le")
        self.db_panel_info_lab = QtWidgets.QLabel(Form)
        self.db_panel_info_lab.setGeometry(QtCore.QRect(30, 240, 186, 39))
        self.db_panel_info_lab.setObjectName("db_panel_info_lab")
        self.db_panel_conn_lab = QtWidgets.QLabel(Form)
        self.db_panel_conn_lab.setGeometry(QtCore.QRect(270, 240, 30, 30))
        self.db_panel_conn_lab.setMinimumSize(QtCore.QSize(30, 30))
        self.db_panel_conn_lab.setMaximumSize(QtCore.QSize(30, 30))
        self.db_panel_conn_lab.setText("")
        self.db_panel_conn_lab.setObjectName("db_panel_conn_lab")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 300, 381, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.db_panel_yes_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_panel_yes_btn.sizePolicy().hasHeightForWidth())
        self.db_panel_yes_btn.setSizePolicy(sizePolicy)
        self.db_panel_yes_btn.setObjectName("db_panel_yes_btn")
        self.horizontalLayout.addWidget(self.db_panel_yes_btn)
        self.db_panel_test_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_panel_test_btn.sizePolicy().hasHeightForWidth())
        self.db_panel_test_btn.setSizePolicy(sizePolicy)
        self.db_panel_test_btn.setObjectName("db_panel_test_btn")
        self.horizontalLayout.addWidget(self.db_panel_test_btn)
        self.db_panel_logo_lab = QtWidgets.QLabel(Form)
        self.db_panel_logo_lab.setGeometry(QtCore.QRect(320, 20, 81, 71))
        self.db_panel_logo_lab.setMinimumSize(QtCore.QSize(50, 50))
        self.db_panel_logo_lab.setObjectName("db_panel_logo_lab")

        self.retranslateUi(Form)
        self.db_panel_yes_btn.clicked.connect(Form.db_connect)
        self.db_panel_test_btn.clicked.connect(Form.db_test)
        self.db_panel_server_cb.currentTextChanged['QString'].connect(Form.ok_btn_disable)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.db_panel_server_lab_2.setText(_translate("Form", "服务器地址"))
        self.db_panel_port_lab.setText(_translate("Form", "端口号"))
        self.db_panel_info_lab.setText(_translate("Form", "服务器连接状态状态"))
        self.db_panel_yes_btn.setText(_translate("Form", "确认"))
        self.db_panel_test_btn.setText(_translate("Form", "测试"))
        self.db_panel_logo_lab.setText(_translate("Form", "Logo"))
